import {
    AccessibilityHelp,
    Autoformat,
    AutoImage,
    AutoLink,
    Autosave,
    BalloonToolbar,
    Base64UploadAdapter,
    BlockQuote,
    Bold,
    Code,
    CodeBlock,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    Highlight,
    HorizontalLine,
    ImageBlock,
    ImageCaption,
    ImageInline,
    ImageInsert,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageTextAlternative,
    ImageToolbar,
    ImageUpload,
    Indent,
    IndentBlock,
    Italic,
    Link,
    LinkImage,
    List,
    ListProperties,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SelectAll,
    SpecialCharacters,
    SpecialCharactersArrows,
    SpecialCharactersCurrency,
    SpecialCharactersEssentials,
    SpecialCharactersLatin,
    SpecialCharactersMathematical,
    SpecialCharactersText,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    TodoList,
    Underline,
    Undo,
    WordCount,
    Bookmark,
    CKBox,
    CKBoxImageEdit,
    CloudServices,
    Emoji,
    Fullscreen,
    GeneralHtmlSupport,
    HtmlEmbed,
    ImageEditing,
    PictureEditing,
    PlainTableOutput,
    ImageUtils,
    Mention,
    PageBreak,
    ShowBlocks,
    TableLayout,
    TextPartLanguage,
    Style,
    MediaEmbed,
    Image,
    Font,
    Alignment,
} from 'ckeditor5'

import {
    CaseChange,
    ExportPdf,
    ExportWord,
    FormatPainter,
    ImportWord,
    LineHeight,
    MergeFields,
    MultiLevelList,
    SlashCommand,
    TableOfContents,
    Template,
} from 'ckeditor5-premium-features'

import 'ckeditor5/ckeditor5.css'
import 'ckeditor5-premium-features/ckeditor5-premium-features.css'

import { WProofreader } from '@webspellchecker/wproofreader-ckeditor5'

import CustomMedia from '../plugins/customMedia'
import CustomMediaEmbed from '../plugins/CustomMediaEmbed'
import {
    CKBOX_TOKEN_URL,
    customMentionUserItemRenderer,
    LICENSE_KEY,
    MERGE_FIELDS_DATASETS,
    MERGE_FIELDS_DEFINITIONS,
    REDUCED_MATERIAL_COLORS,
    TEMPLATE_DEFINITIONS,
    WEB_SPELL_CHECKER_LICENSE_KEY,
} from './constant'
import CustomImageGallery from '../plugins/CustomImageGallery'

export const ConfigRichTextEditor: any = {
    licenseKey: 'GPL',
    toolbar: {
        shouldNotGroupWhenFull: true,
        items: [
            'undo',
            'redo',
            '|',
            'insertMergeField',
            'previewMergeFields',
            '|',
            'importWord',
            'exportWord',
            'exportPdf',
            '|',
            'formatPainter',
            'caseChange',
            'findAndReplace',
            'selectAll',
            '|',
            'insertTemplate',
            'tableOfContents',
            '|',
            'heading',
            '|',
            'fontSize',
            'fontFamily',
            'fontColor',
            'fontBackgroundColor',
            '|',
            'bold',
            'italic',
            'underline',
            'strikethrough',
            'subscript',
            'superscript',
            'code',
            'removeFormat',
            'highlight',
            '|',
            'insertImage',
            'customMedia',
            'customImageGallery',
            'ckbox',
            'mediaEmbed',
            '|',
            'blockQuote',
            'emoji',
            'specialCharacters',
            'horizontalLine',
            'pageBreak',
            'link',
            // 'bookmark',
            '|',
            'insertTable',
            'insertTableLayout',
            'alignment:left',
            'alignment:center',
            'alignment:right',
            'alignment:justify',
            '|',
            'bulletedList',
            'numberedList',
            'todoList',
            'outdent',
            'indent',
            '|',
            'fullscreen',
        ],
    },
    plugins: [
        SelectAll,
        Undo,
        AccessibilityHelp,
        Base64UploadAdapter,
        Autoformat,
        AutoImage,
        AutoLink,
        Autosave,
        BalloonToolbar,
        BlockQuote,
        Bold,
        Bookmark,
        CKBox,
        CKBoxImageEdit,
        CloudServices,
        Code,
        CodeBlock,
        Emoji,
        Essentials,
        FindAndReplace,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        Fullscreen,
        GeneralHtmlSupport,
        Heading,
        Highlight,
        HorizontalLine,
        HtmlEmbed,
        ImageBlock,
        ImageCaption,
        ImageEditing,
        ImageInline,
        ImageInsert,
        ImageInsertViaUrl,
        ImageResize,
        ImageStyle,
        ImageTextAlternative,
        ImageToolbar,
        ImageUpload,
        ImageUtils,
        Indent,
        IndentBlock,
        Italic,
        Link,
        LinkImage,
        List,
        ListProperties,
        Mention,
        PageBreak,
        Paragraph,
        PasteFromOffice,
        PictureEditing,
        PlainTableOutput,
        RemoveFormat,
        ShowBlocks,
        SpecialCharacters,
        SpecialCharactersArrows,
        SpecialCharactersCurrency,
        SpecialCharactersEssentials,
        SpecialCharactersLatin,
        SpecialCharactersMathematical,
        SpecialCharactersText,
        Strikethrough,
        Subscript,
        Superscript,
        Table,
        TableCaption,
        TableCellProperties,
        TableColumnResize,
        TableLayout,
        TableProperties,
        TableToolbar,
        TextPartLanguage,
        TextTransformation,
        TodoList,
        Underline,
        WordCount,
        Style,
        MediaEmbed,
        Image,
        Font,
        Alignment,

        // Custom modal plugin
        CustomMedia,
        CustomMediaEmbed,
        CustomImageGallery,

        // Include CKBox plugin only if the CKBOX_TOKEN_URL is provided.
        ...(CKBOX_TOKEN_URL ? [CKBox] : []),

        // Include premium features only if the license key is not GPL.
        ...(LICENSE_KEY !== 'GPL'
            ? [
                  CaseChange,
                  ExportPdf,
                  ExportWord,
                  FormatPainter,
                  ImportWord,
                  MergeFields,
                  MultiLevelList,
                  SlashCommand,
                  TableOfContents,
                  Template,
                  LineHeight,
              ]
            : []),

        // Include WebSpellChecker plugin only if the WEB_SPELL_CHECKER_LICENSE_KEY is provided.
        ...(WEB_SPELL_CHECKER_LICENSE_KEY ? [WProofreader] : []),
    ],
    balloonToolbar: [
        'bold',
        'italic',
        '|',
        'link',
        'insertImage',
        '|',
        'bulletedList',
        'numberedList',
    ],
    fontFamily: {
        options: ['default', 'Roboto, Arial, sans-serif'],
        supportAllValues: false, // 🔥 MUHIM
    },
    fontSize: {
        options: [10, 12, 14, 'default', 18, 20, 22],
        supportAllValues: true,
    },
    fontColor: {
        columns: 12,
        colors: REDUCED_MATERIAL_COLORS,
    },
    fontBackgroundColor: {
        columns: 12,
        colors: REDUCED_MATERIAL_COLORS,
    },
    heading: {
        options: [
            {
                model: 'paragraph',
                title: 'Paragraph',
                class: 'ck-heading_paragraph',
            },
            {
                model: 'heading1',
                view: 'h1',
                title: 'Heading 1',
                class: 'ck-heading_heading1',
            },
            {
                model: 'heading2',
                view: 'h2',
                title: 'Heading 2',
                class: 'ck-heading_heading2',
            },
            {
                model: 'heading3',
                view: 'h3',
                title: 'Heading 3',
                class: 'ck-heading_heading3',
            },
            {
                model: 'heading4',
                view: 'h4',
                title: 'Heading 4',
                class: 'ck-heading_heading4',
            },
            {
                model: 'heading5',
                view: 'h5',
                title: 'Heading 5',
                class: 'ck-heading_heading5',
            },
            {
                model: 'heading6',
                view: 'h6',
                title: 'Heading 6',
                class: 'ck-heading_heading6',
            },
        ],
    },
    image: {
        toolbar: [
            'toggleImageCaption',
            'imageTextAlternative',
            '|',
            'imageStyle:inline',
            'imageStyle:wrapText',
            'imageStyle:breakText',
            '|',
            'resizeImage',
            '|',
            'ckboxImageEdit',
        ],

        resizeOptions: [
            {
                name: 'resizeImage:original',
                label: 'Original',
                value: null,
            },
            {
                name: 'resizeImage:25',
                label: '25%',
                value: '25',
            },
            {
                name: 'resizeImage:50',
                label: '50%',
                value: '50',
            },
            {
                name: 'resizeImage:75',
                label: '75%',
                value: '75',
            },
            {
                name: 'resizeImage:100',
                label: '100%',
                value: '100',
            },
        ],
    },
    link: {
        decorators: {
            toggleDownloadable: {
                mode: 'manual',
                label: 'Downloadable',
                attributes: {
                    download: 'file',
                },
            },
        },
        addTargetToExternalLinks: true,
        defaultProtocol: 'https://',
    },
    list: {
        properties: {
            styles: true,
            startIndex: true,
            reversed: true,
        },
    },
    table: {
        contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableProperties',
            'tableCellProperties',
            'toggleTableCaption',
        ],
    },
    mention: {
        feeds: [
            {
                marker: '@',
                feed: [
                    { id: '@cflores', avatar: 'm_1', name: 'Charles Flores' },
                    { id: '@gjackson', avatar: 'm_2', name: 'Gerald Jackson' },
                    { id: '@wreed', avatar: 'm_3', name: 'Wayne Reed' },
                    { id: '@lgarcia', avatar: 'm_4', name: 'Louis Garcia' },
                    { id: '@rwilson', avatar: 'm_5', name: 'Roy Wilson' },
                    { id: '@mnelson', avatar: 'm_6', name: 'Matthew Nelson' },
                    { id: '@rwilliams', avatar: 'm_7', name: 'Randy Williams' },
                    { id: '@ajohnson', avatar: 'm_8', name: 'Albert Johnson' },
                    { id: '@sroberts', avatar: 'm_9', name: 'Steve Roberts' },
                    { id: '@kevans', avatar: 'm_10', name: 'Kevin Evans' },
                    { id: '@vxiques', avatar: 'm_11', name: 'Vincent Xiques' },
                    { id: '@jzaldivar', avatar: 'm_12', name: 'Jack Zaldivar' },
                    {
                        id: '@tfoxworth',
                        avatar: 'm_13',
                        name: 'Thomas Foxworth',
                    },
                    { id: '@phendrix', avatar: 'm_14', name: 'Peter Hendrix' },
                    { id: '@pthaxton', avatar: 'm_15', name: 'Philip Thaxton' },
                    { id: '@mwilson', avatar: 'w_1', name: 'Mildred Wilson' },
                    { id: '@mnelson', avatar: 'w_2', name: 'Melissa Nelson' },
                    { id: '@kallen', avatar: 'w_3', name: 'Kathleen Allen' },
                    { id: '@myoung', avatar: 'w_4', name: 'Mary Young' },
                    { id: '@arogers', avatar: 'w_5', name: 'Ashley Rogers' },
                    { id: '@dgriffin', avatar: 'w_6', name: 'Debra Griffin' },
                    {
                        id: '@dwilliams',
                        avatar: 'w_7',
                        name: 'Denise Williams',
                    },
                    { id: '@ajames', avatar: 'w_8', name: 'Amy James' },
                    { id: '@randerson', avatar: 'w_9', name: 'Ruby Anderson' },
                    { id: '@wlee', avatar: 'w_10', name: 'Wanda Lee' },
                    { id: '@yquick', avatar: 'w_11', name: 'Yasmin Quick' },
                    {
                        id: '@bzappaterra',
                        avatar: 'w_12',
                        name: 'Beatrice Zappaterra',
                    },
                    { id: '@zquigley', avatar: 'w_13', name: 'Zoe Quigley' },
                    {
                        id: '@pfabozzi',
                        avatar: 'w_14',
                        name: 'Patrizia Fabozzi',
                    },
                    { id: '@vquimby', avatar: 'w_15', name: 'Victoria Quimby' },
                ],
                minimumCharacters: 1,
                itemRenderer: customMentionUserItemRenderer,
            },
            {
                marker: '#',
                feed: [
                    '#american',
                    '#asian',
                    '#baking',
                    '#breakfast',
                    '#cake',
                    '#caribbean',
                    '#chinese',
                    '#chocolate',
                    '#cooking',
                    '#dairy',
                    '#delicious',
                    '#delish',
                    '#dessert',
                    '#desserts',
                    '#dinner',
                    '#eat',
                    '#eating',
                    '#eggs',
                    '#fish',
                    '#food',
                    '#foodie',
                    '#foods',
                    '#french',
                    '#fresh',
                    '#fusion',
                    '#glutenfree',
                    '#greek',
                    '#grilling',
                    '#halal',
                    '#homemade',
                    '#hot',
                    '#hungry',
                    '#icecream',
                    '#indian',
                    '#italian',
                    '#japanese',
                    '#keto',
                    '#korean',
                    '#lactosefree',
                    '#lunch',
                    '#meat',
                    '#mediterranean',
                    '#mexican',
                    '#moroccan',
                    '#nom',
                    '#nomnom',
                    '#paleo',
                    '#poultry',
                    '#snack',
                    '#spanish',
                    '#sugarfree',
                    '#sweet',
                    '#sweettooth',
                    '#tasty',
                    '#thai',
                    '#vegan',
                    '#vegetarian',
                    '#vietnamese',
                    '#yum',
                    '#yummy',
                ],
            },
        ],
    },
    style: {
        definitions: [
            {
                name: 'Title',
                element: 'h1',
                classes: ['document-title'],
            },
            {
                name: 'Subtitle',
                element: 'h2',
                classes: ['document-subtitle'],
            },
            {
                name: 'Callout',
                element: 'p',
                classes: ['callout'],
            },
            {
                name: 'Side quote',
                element: 'blockquote',
                classes: ['side-quote'],
            },
            {
                name: 'Needs clarification',
                element: 'span',
                classes: ['needs-clarification'],
            },
            {
                name: 'Wide spacing',
                element: 'span',
                classes: ['wide-spacing'],
            },
            {
                name: 'Small caps',
                element: 'span',
                classes: ['small-caps'],
            },
            {
                name: 'Code (dark)',
                element: 'pre',
                classes: ['stylish-code', 'stylish-code-dark'],
            },
            {
                name: 'Code (bright)',
                element: 'pre',
                classes: ['stylish-code', 'stylish-code-bright'],
            },
        ],
    },
    wproofreader: {
        serviceId: WEB_SPELL_CHECKER_LICENSE_KEY,
        lang: 'auto',
        srcUrl: 'https://svc.webspellchecker.net/spellcheck31/wscbundle/wscbundle.js',
        autoStartup: false,
    },
    // ckbox: {
    //     tokenUrl: CKBOX_TOKEN_URL,
    // },
    template: {
        definitions: TEMPLATE_DEFINITIONS,
    },
    menuBar: {
        isVisible: true,
    },
    mergeFields: {
        definitions: MERGE_FIELDS_DEFINITIONS,
        dataSets: MERGE_FIELDS_DATASETS,
    },
    htmlSupport: {
        allow: [
            {
                name: /.*/,
                attributes: true,
                classes: true,
                styles: true,
            },
            {
                name: 'video',
                attributes: true,
                classes: true,
                styles: true,
            },
            {
                name: 'source',
                attributes: true,
            },
            {
                name: 'iframe',
                attributes: true,
                classes: true,
                styles: true,
            },
            {
                name: 'div',
                attributes: true,
                classes: true,
                styles: true,
            },
            {
                name: 'figure',
                attributes: true,
                classes: true,
                styles: true,
            },
        ],
        disallow: [
            {
                name: /.*/,
                styles: ['font-family'], // 🔥 shu style endi kirmaydi
            },
        ],
    },
    lineHeight: {
        options: [
            1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.5, 3, 3.5, 4,
            5,
        ],
    },
}
